Package Sintactico;

import java_cup.runtime.*;
import java.io.*;
import java.util.*;

parser code {:|
    public void syntax_error(Symbol s) {
        System.out.println("CUP detecto un error de syntaxis en " + s.left + " column " + s.right);
    }
:}

// => Ahorita solo se probará la asignación OwO

// => Terminales
terminal String BOOL, CHAR, INT, EMPTY;
terminal MAIN, IF, ELSE, ORELSE, FOR, WHILE, SWITCH, CASE, DEFAULT, FUNCTION,
        COMEBACK, BREAK, NUMBER, BOOLEAN, CHARACTER, ARRAY, INPUT, OUTPUT,
        OPREL, SUM, RES, MULT, DIV, MOD, SEMICOLON, COLON, COMMA, PARDER,
        PARIZQ, BRACKETDER, BRACKETIZQ, SBRACKETDER, SBRACKETIZQ, ASSIGNMENT, ID;

// => No terminales
no terminal Inicio;
no terminal body;

start with Inicio;

Inicio ::=  FUNCTION MAIN PARIZQ PARDER ASSIGNMENT BRACKETIZQ body BRACKETDER;
body ::= proposition;