
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package main;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FUNCTION = 16;
  public static final int ORELSE = 10;
  public static final int MULT = 28;
  public static final int CHAR = 3;
  public static final int ASSIGNMENT = 40;
  public static final int EMPTY = 5;
  public static final int OUTPUT = 24;
  public static final int RES = 27;
  public static final int INPUT = 23;
  public static final int CASE = 14;
  public static final int SBRACKETDER = 38;
  public static final int INT = 4;
  public static final int COMEBACK = 17;
  public static final int ARRAY = 22;
  public static final int FOR = 11;
  public static final int CHARACTER = 21;
  public static final int SEMICOLON = 31;
  public static final int BOOL = 2;
  public static final int COMMA = 33;
  public static final int DELIMETER = 42;
  public static final int DIV = 29;
  public static final int OPREL = 25;
  public static final int MAIN = 6;
  public static final int IF = 7;
  public static final int ID = 41;
  public static final int PARIZQ = 35;
  public static final int EOF = 0;
  public static final int BOOLEAN = 20;
  public static final int BRACKETIZQ = 37;
  public static final int error = 1;
  public static final int NUMBER = 19;
  public static final int MOD = 30;
  public static final int BREAK = 18;
  public static final int SWITCH = 13;
  public static final int COLON = 32;
  public static final int ELSE = 9;
  public static final int SBRACKETIZQ = 39;
  public static final int WHILE = 12;
  public static final int DEFAULT = 15;
  public static final int THEN = 8;
  public static final int SUM = 26;
  public static final int PARDER = 34;
  public static final int BRACKETDER = 36;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BOOL",
  "CHAR",
  "INT",
  "EMPTY",
  "MAIN",
  "IF",
  "THEN",
  "ELSE",
  "ORELSE",
  "FOR",
  "WHILE",
  "SWITCH",
  "CASE",
  "DEFAULT",
  "FUNCTION",
  "COMEBACK",
  "BREAK",
  "NUMBER",
  "BOOLEAN",
  "CHARACTER",
  "ARRAY",
  "INPUT",
  "OUTPUT",
  "OPREL",
  "SUM",
  "RES",
  "MULT",
  "DIV",
  "MOD",
  "SEMICOLON",
  "COLON",
  "COMMA",
  "PARDER",
  "PARIZQ",
  "BRACKETDER",
  "BRACKETIZQ",
  "SBRACKETDER",
  "SBRACKETIZQ",
  "ASSIGNMENT",
  "ID",
  "DELIMETER"
  };
}

